### ISSUE TITLE
Add a LICENSE to  WPIWebSocketsTemplate

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/WPIWebSocketsTemplate#1]
See:

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by CoolSpy3** [comment]
Which license template should we add to the repo?

**Comment by brettle** [comment]
I personally recommend MIT, to make it as easy as possible for others to
use.
